name: Release

# This workflow releases the docker image and deploy it on staging

on:
  push:
    branches:
      - release
    # tags:
    # - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: |
          make docker

      - name: Docker image info
        run: docker images

      - name: Login to container registries
        run: |
          echo ${{ secrets.GH_PERSONAL_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/phaser
